In [4]:
import pandas as pd

In [5]:
df=pd.read_csv(r"NLP-Learning\datasets\FakeNews\train.csv.csv") ## using fake news data from NLP

FileNotFoundError: [Errno 2] No such file or directory: 'NLP-Learning\\datasets\\FakeNews\\train.csv.csv'

In [38]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [39]:
# ## get the independent features
# X=df.drop('label', axis = 1)
# y=df['label']


df = df.dropna(subset=['title'])
df = df.reset_index(drop=True)

X = df.drop('label', axis=1)
y = df['label']

messages = X.copy()

In [40]:
## check if dataset is balanced or not
y.value_counts()

label
0    10387
1     9855
Name: count, dtype: int64

In [41]:
import tensorflow as tf

In [42]:
tf.__version__

'2.20.0'

In [43]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Dense, Bidirectional

In [44]:
## vocabulary size
voc_size = 5000

In [45]:
# messages=X.copy()

In [46]:
import nltk
import re
from nltk.corpus import stopwords

In [47]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [48]:
from nltk import PorterStemmer
ps = PorterStemmer()

corpus = []
# messages = messages.dropna(subset=['title'])
# messages = messages.reset_index(drop=True)
for i in range(0, len(messages)):
  # print(i)
  # print(type(messages['title'].iloc[i]))
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)

  corpus.append(review)

In [49]:
corpus[:5]

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri']

In [50]:
one_hot_repr = [one_hot(words, voc_size) for words in corpus]
print(one_hot_repr)

[[2310, 2251, 984, 2564, 4055, 3348, 2681, 2412, 2630, 3918], [4870, 3749, 1505, 91, 2456, 2000, 2399], [2922, 2311, 288, 1663], [4127, 2572, 786, 3893, 1584, 4061], [947, 2456, 4198, 585, 511, 3167, 2456, 4342, 613, 3413], [88, 3105, 4004, 4406, 2269, 2552, 3692, 3076, 1411, 633, 2925, 315, 1057, 313, 2399], [17, 17, 1621, 775, 485, 3929, 752, 702, 1990, 1491, 2293, 3283], [4819, 4129, 479, 1431, 278, 2977, 1191, 1750, 4977, 3759, 3624], [4243, 500, 1798, 1631, 2552, 955, 4516, 4956, 2041, 1229, 4977, 3759, 3624], [4345, 3248, 3147, 3426, 1802, 1479, 2552, 328, 4977, 3759, 3624], [4685, 1047, 4106, 1488, 4573, 4210, 3236, 4750, 2552, 1905], [868, 1577, 839, 2318, 1206, 4956, 3987, 1724], [3229, 4985, 4726, 3383, 548, 2403, 2380, 2997, 4587, 3748, 4690], [3893, 1799, 4055, 4210, 2552, 1802], [2381, 2452, 4738, 1483, 4438, 732, 4342, 4485, 2046], [4931, 1746, 1662, 1994, 259, 2397, 2344, 4977, 3759, 3624], [2406, 4298, 1733, 4706, 2522, 4977, 3759, 3624], [4025, 2002, 4282, 1760, 3091, 2343, 2674, 194, 368, 4128], [3213, 1767, 3749], [3471, 2208, 20, 1631, 2552, 1256, 4597, 2399], [3718, 4584, 951, 2238, 3812, 388, 4867, 2267, 4880, 2830, 4977, 226, 2977], [1666, 4435, 1505, 529, 1949, 525, 1058, 4683, 3167], [2617, 4639, 2552, 1673, 2941, 2399], [1033, 3767, 2468, 2107, 3514, 2038, 2397, 4133, 4958, 4956, 3022, 4193], [375, 4130, 2377, 4630, 4184, 1058, 581, 1733, 3203, 4977, 3759, 3624], [2214, 658, 4335, 2899, 3925, 4702, 64], [1057, 2683, 1699, 317, 3097, 348, 779, 4038, 3421, 1035, 3002, 2399], [1880, 3749, 2724, 2001, 1354, 534, 3130, 2940], [4292, 4665, 3217, 3718, 3463, 3407, 529, 2742, 2652, 4977, 3759, 3624], [3749, 1505, 4804, 4600, 4977, 3759, 3624], [3471, 2208, 20, 3878, 2936, 2038, 3718, 2399], [3269, 1890, 338, 3452, 4071, 3952, 1062, 859, 2139, 1708, 1177, 3269, 1890, 338, 3452, 4071, 3952, 1062], [1118, 3083, 4841, 128, 91, 4977, 3759, 3624], [4723, 3270, 1118, 4243, 4060, 3299, 1, 1067, 211, 4977, 3759, 3624], [2024, 3629, 188, 4038, 2564, 3324, 4253, 904, 95, 4977, 3759, 3624], [1802, 4656, 3925, 4421, 4731, 2587, 4977, 3759, 3624], [146, 342, 4120, 657, 940], [336, 3302, 3384, 2204], [1530, 98, 2152, 512, 2690, 2141, 4320, 2399], [1141, 1921, 1141, 4788, 2228, 713, 4977, 3759, 3624], [245, 2372, 2018, 2293, 4704, 96, 1255, 2399], [4258, 3591, 3412, 1576], [388, 2255, 4075, 73, 826, 2886, 4977, 3759, 3624], [70, 1683, 163, 86, 2128, 345, 2420, 291], [1636, 1887, 3709, 1274, 4685, 2165, 908, 634, 2399], [1019, 4472, 460, 3951, 2272, 1025, 3217, 4977, 3759, 3624], [695, 2935, 3237, 2592, 1200, 786, 4734, 380, 313], [], [842, 968, 4572, 3485, 60, 4977, 4298, 4977, 3759, 3624], [4153, 3097, 2021, 1503, 758, 1941, 1226, 933, 389, 3063, 4689, 2399], [4966, 4582, 1041], [4129, 1306, 2384, 296, 1802, 1292], [4873, 4149, 42, 4163, 3655, 2787, 970, 1456, 3790, 2399], [399, 439, 1084, 342, 4630, 2418, 908, 1058, 1256, 313], [2552, 2204, 4966, 2408, 451, 1515], [3103, 2154, 4956, 2455, 2041, 2098, 156, 3291, 3341, 2890, 313], [3740, 4431, 2683, 824, 14], [1631, 2552, 479, 2204, 2254, 581, 3893, 1256, 1688], [118, 504, 2468, 494, 1254, 4977, 3759, 3624], [4931, 704, 2107, 3862, 4758, 4742, 4977, 3759, 3624], [2360, 3527, 414, 583, 2204], [460, 768, 4487, 356, 1645, 2996, 2511, 4821, 4977, 3759, 3624], [826, 3231, 2552, 1790, 3570, 4414, 2949, 3022, 4447], [14, 2347, 4511, 4930, 2757, 4624, 4351, 3932, 1388, 4977, 3759, 3624], [3384, 2899, 2683, 1699, 2488, 1424, 2107, 3384, 4271], [916, 259, 920, 1951, 3659, 3170, 632, 4814, 2690, 809], [1505, 2474, 1128, 3213, 3172, 4393, 300, 3749, 1505, 4927], [4439, 3876, 3231, 375, 2940, 4977, 3759, 3624], [4303, 2467, 865, 732, 2552, 3381, 1256, 3556], [3793, 768, 3860, 3106], [3710, 1032, 3097, 3440, 1671], [4297, 414, 2456, 3709, 4977, 3759, 3624], [1852, 770, 146, 113, 741, 4977, 1420, 4977, 3759, 3624], [695, 3256, 1905, 4685, 1263, 1543, 4003, 908, 4977, 3759, 3624], [1530, 4729, 2577, 4077, 2324, 4977, 3759, 3624], [3718, 371, 4906, 380, 2621, 4271, 2041, 2621, 2935, 2870, 809, 163, 1576], [2111, 1015, 791, 4375, 4685, 1081, 1827, 3718], [3384, 3775, 1887, 575, 3625, 1258, 4977, 3759, 3624], [1790, 281, 3048, 1524, 2552, 911, 530, 2399], [2124, 3858, 2791, 3384, 1191, 2114, 3940, 2564, 449, 4977, 3759, 3624], [718, 4579, 336, 1503, 1244, 4487, 4420, 1864, 1161], [2836, 357, 1798, 3749], [3817, 607, 1736, 4956, 231, 3479, 4682, 1717, 2438], [2552, 3567, 1830, 4779, 4977, 3759, 3624], [2218, 2220, 943, 1208, 3531, 1716, 4382, 4616, 4977, 3759, 3624], [2235], [2552, 2939, 2940, 1461, 581, 317, 380, 4977, 3759, 3624], [3217, 1490, 1671, 160, 3479, 1505, 2940, 221, 2552, 563, 4048, 583], [585, 1695, 2598, 4400, 4977, 3759, 3624], [1573, 2115, 3664, 3793, 1639, 4004, 2918, 4977, 3759, 3624], [76, 3802, 2190, 4608, 1073, 614, 2589, 4667, 4171, 2619], [4181, 469, 1558, 4656, 2501, 70, 4463, 4733, 4977, 3759, 3624], [2547, 485, 431, 2187, 3092, 1631, 2552, 1530, 458, 2122, 1266, 597, 724, 1902, 226, 2160], [2399, 3718, 3860, 2552, 4552, 2399], [3414, 2310, 3262, 353, 2312, 4685, 1241, 377], [4632, 4376, 2651, 131], [3162, 4409, 4689, 1530, 2204, 2160, 2399], [1503, 112, 1789, 583, 2044, 3436, 2377, 4977, 3759, 3624], [2565, 3384, 4913, 241, 2708, 3147, 3423, 4977, 3759, 3624], [3347, 2318, 1576, 658, 3223, 3704, 2220], [1058, 2787, 4831, 2046, 4030, 1010, 4977, 3759, 3624], [3749, 1505, 1642, 1760, 1266, 3016, 1224, 1631, 2552, 4977, 3759, 3624], [2552, 4528, 3352, 1671, 2509, 3841, 568, 2010], [2324, 4553, 3229, 4738, 4704], [2293, 320, 3668, 2876, 194, 368, 4128], [4818, 1699, 3924, 936, 2093, 3090, 3126, 3924, 936, 2093, 2399], [1074, 4271, 1642, 1455, 2403, 2380, 651, 1802, 3718], [4327, 91, 3765, 588, 2396, 4723, 315, 121, 2399], [826, 1586, 989, 3618, 3885, 2998, 2910, 3872, 4859, 1387, 2399], [2932, 2526, 4608, 525, 708, 4791, 4251, 4456, 91, 2372, 4977, 3759, 3624], [1540, 551, 2788, 3498, 1009, 2552, 4923, 4050, 1094, 2791], [3001, 2552, 481, 1410, 4429, 357, 4086, 368, 4955, 2736, 313, 3451, 226], [4147, 2873, 1605, 3522, 2755, 1762, 1059, 4964, 4977, 3759, 3624], [1505, 2474, 3883, 1749, 2592, 3731, 1799, 70, 583, 3749, 1786, 286], [2935, 3361, 3872, 3108, 3547, 2729, 3511, 70, 66, 2527, 2929, 2399], [3422, 4258, 4018, 597, 3603, 1451, 3022, 334, 60, 4977, 3759, 3624], [3560, 2872, 581, 850, 3130, 2443, 4977, 3759, 3624], [14, 70, 3793, 424, 975, 2793, 4977, 3759, 3624], [2552, 2420, 2803, 2384, 2403, 1902, 1799, 865, 4977, 3759, 3624], [2362, 1917, 2690, 4927, 3237, 1274, 4685, 3749, 4927], [3322, 2866, 2310, 4977, 1067, 2968, 1695, 1714, 4150, 908, 808], [3799, 675, 3452, 3198, 3528, 3799, 4815, 4977, 3759, 3624], [559, 4843, 820, 2310, 3038, 2619, 3394], [3027, 4396, 1236, 3841, 3893, 2204, 1159, 2528, 3749, 479], [1768, 2099, 4644, 1571, 3858, 4349, 4977, 3759, 3624], [1767, 4263, 101, 3484, 1890, 3791, 2864, 4977, 3759, 3624], [2935, 1942, 2129, 3414, 2310, 2950, 1631, 2552, 2399], [4232, 226, 4088, 2552, 4511, 2293, 380, 2399], [416, 1661, 768, 1757, 3089], [788, 2552, 3718, 4704, 4964, 4977, 3759, 3624], [1631, 2552, 60, 3147, 1855, 4810, 597, 4253, 4977, 3759, 3624], [1226, 1035, 160, 2860, 1258, 7, 4479, 3101, 761], [3213, 1003, 3348, 137, 4265, 4779, 4393, 1505, 4927, 1035], [2373, 1530, 4253, 121, 3925, 2042, 538, 281, 2784, 2399], [188, 996, 2278, 3743], [2176, 2225, 2527, 583, 1058], [1799, 3858, 2791, 768, 4258, 4316, 4977, 3759, 3624], [4450, 2434, 971, 2574, 4667, 1911, 2983, 3733, 1090], [3723, 4559, 3792, 1028, 389, 1269, 4685, 4585, 3635, 462, 3881, 3930, 1277, 3723], [3384, 2565, 3827, 2899, 1540, 219, 963, 2940, 4597, 581], [2552, 3171, 460, 4309, 4068, 4730, 1058, 4409, 3833, 4352, 313], [3213, 259, 3536, 1927, 3749, 1505, 4927, 357, 3821], [4251, 1058, 2077, 2572, 4814, 2734, 1258, 4901, 433], [1671, 4086, 3206, 3705, 4359, 3273, 1411, 2552, 2168], [3793, 3637, 2087, 3576, 2342, 3563], [1451, 2572, 1480, 1660, 4804, 1009, 4910, 1424], [128, 2115, 798, 4429, 2848, 2932, 1261, 2526, 307, 4238, 4225], [3498, 4956, 2380, 28, 463, 1323, 1790, 4785, 1122, 4427], [2774, 2298, 2690, 3704, 70, 4465, 4682, 4495, 4919, 583, 2630], [4630, 2220, 2939, 2183, 4977, 3759, 3624], [436, 983, 4818, 1247, 2552, 1997, 2190, 4977, 3759, 3624], [1003, 1850, 4119, 2527, 3612, 3147, 1932, 2384, 4977, 3759, 3624], [3783, 1405], [394, 791, 3414, 2310, 1504, 877, 4002, 1720, 4977, 3759, 3624], [3811, 3080, 1663, 1524, 3383, 4298, 2552, 596, 3918, 2399], [1505, 803], [864, 4865, 3324, 1454, 2592, 238, 28, 4977, 3759, 3624], [2592, 3939, 768, 2788, 4037], [4977, 4873, 4210, 3560, 2669, 4563, 2611, 87, 940], [4205, 1796, 3827, 381], [4956, 2041, 4568, 1622, 2451, 4253, 2552], [3233, 2566, 4745, 4928, 4150, 4956, 144, 656, 4253, 1392, 4977, 3759, 3624], [1022, 1733, 3106, 2041, 989, 933, 1133, 4977, 3759, 3624], [3191, 2001, 4956, 1760, 4977, 3759, 3624], [1304, 1729, 4043, 524, 2107, 1285, 4958, 2399], [3884, 1534, 2527, 1110, 4463, 3071, 1058, 2093, 809, 4910], [3781, 761, 3859, 1283], [4060, 4972, 3974, 4433, 940, 989, 2399], [897, 4352, 3176, 3172, 2813, 2555], [2552, 1855, 4203, 1105, 4054, 2038, 4710, 1244, 4422], [2459, 1812, 2949, 2087, 200, 2147, 1017, 2165, 908, 2820, 4601, 865, 1799, 3011, 1631, 2552, 2399], [106, 3642, 4919, 2694, 3892, 352], [588, 2935, 2932, 226, 3574, 1631, 2552, 3218, 4977, 3759, 3624], [336, 2681, 2552, 4409, 929, 414], [3998, 3446, 3862, 1826, 3713, 4345, 3749, 4433, 761, 4906], [1540, 546, 288, 208, 2493, 4369, 2122], [1070, 4846, 3349, 2647, 854, 1244, 2693, 4977, 3759, 3624], [414, 3496, 3496, 1043, 4977, 3759, 3624], [1275, 865, 2872, 543, 946, 1605, 1757, 724, 4977, 3759, 3624], [4889, 4738, 4271, 1179, 1258, 3809, 761, 3384, 1802, 1365, 4977, 3759, 3624], [2805, 4973, 1663, 3084, 1989, 2518, 1651], [2820, 4462, 2247, 2820, 4977, 3759, 3624], [1658, 252, 543, 4030, 1614, 3458, 1973, 1671], [143, 349, 761, 2310, 380, 2204, 2552, 4977, 3759, 3624], [655, 3384, 1681, 494, 3390, 381, 2619, 1663], [3977, 4491, 1266, 511, 288, 4583, 1371, 3549, 2310, 2093, 1099, 288, 1817, 3989, 1621, 1294, 2397], [2757, 494, 1266, 1003, 4081, 994, 4345, 4086, 936, 3765, 994], [1683, 2552, 2873, 2980, 4977, 3759, 3624], [3213, 1003, 3348, 1078, 3731, 4806, 1505], [4359, 3193, 3615, 303, 2141, 1579, 1424], [613, 824, 1699, 3394], [588, 1096, 1185, 1424, 2674, 3349, 1790, 2630, 3464, 1031, 325], [3998, 1143, 3505, 4477, 42, 3767, 2129, 2572, 4826], [2474, 1336, 4760, 3364, 4490, 2190, 543, 3952], [1631, 2552, 4186, 2372, 389, 938, 2204, 4160, 4977, 3759, 3624], [4878, 2569, 2724, 864, 2901, 1157, 3417, 331, 1411, 4977, 3759, 3624], [4666, 4007, 4919, 220, 3918, 4727, 3626, 2805], [1631, 2552, 4457, 2160, 4977, 3759, 3624], [225, 4977, 4088, 3749, 460, 2474, 1576, 3924, 3893, 1266, 4558, 2314, 2189], [447, 3893, 4639], [1057, 1855, 3037, 3484, 4461, 2103, 60, 3509, 865, 2636, 1647, 4337, 2318, 3922, 2010], [2552, 4088, 1671, 2458, 2820, 2420, 3269, 2399], [1058, 2018, 4791, 4251], [172, 1736, 695, 760, 4730, 4601, 4977, 3759, 3624], [1983, 4007, 2156, 3361], [658, 3147, 1473, 2343, 2073, 2474, 1306], [2552, 1424, 2324, 861, 4676, 3998, 4977, 3759, 3624], [1505, 322, 136, 137, 4927, 3749, 4086, 536], [2134, 3362, 3812, 388, 2837, 908, 2399], [1631, 2552, 2152, 4667, 4163], [4977, 768, 2377, 4689, 4345, 4841, 1041], [4538, 2278, 3937, 4266, 4765, 2473, 2862, 2397, 4830], [2292, 2324, 2114, 439, 3355, 3350, 3217, 2965, 4977, 3759, 3624], [1057, 3791, 865, 2932, 2526, 4406, 4234, 4345, 3217, 3718], [3001, 2864, 4685, 3401, 2427, 154, 1499, 1728, 583, 4977, 3759, 3624], [4841, 4253, 2278, 1101, 4869, 1605, 4215, 1956, 4977, 3759, 3624], [3759, 3037, 2819, 2228, 3718, 2552], [4681, 2757, 4352, 1067, 2968, 2064, 2939, 3496, 4824, 4836, 288, 368, 3240, 3383], [3546, 3384, 1401, 4420, 1266, 4977, 3759, 3624], [3444, 4551, 3672, 3007, 4111, 4153, 1424, 4977, 3759, 3624], [470, 1530, 55, 3126, 2474, 2278, 2552], [1003, 2910, 4253, 2527, 1605, 2497, 4977, 3759, 3624], [1802, 2551, 1424, 156, 649, 865, 4743, 911], [], [2128, 1524, 4860, 3283, 3655, 4480, 2186, 4977, 3759, 3624], [2420, 2614, 2343, 3074], [1003, 4253, 3261, 4119, 2527, 1571, 1608, 3455, 4977, 3759, 3624], [1563, 4088, 2565, 1655, 403, 4921, 1977, 1563, 3766, 1655, 403, 2072, 477, 998], [2552, 3839, 3718, 732, 4977, 713, 2416, 221, 4977, 3759, 3624], [527, 1266, 4383, 3106, 3640, 64, 2828], [1354, 1107, 128, 1354, 147], [3384, 2665, 575, 1319, 2923, 128, 4977, 3759, 3624], [3384, 2543, 1159, 2153, 2924, 1424, 1268, 4977, 3759, 1110, 4723], [929, 3983, 2087, 1719, 893], [1671, 2932, 2526, 2551, 1396, 2372, 4643, 1855, 3841], [3635, 4729, 1605, 4517, 1051, 4977, 3759, 3624], [4878, 1122, 4427, 4865, 4063, 3977, 4063, 4779, 4427, 2552, 48, 4406, 1354, 1256, 2806], [341, 2324, 2406, 4298, 1733, 1537, 4493, 4977, 3759, 3624], [4688, 341, 2473, 1264, 20, 2038, 3718, 2993, 2399], [3071, 4185, 3181, 4977, 4225, 2552, 4733, 4977, 3759, 3624], [141, 1618, 337, 4736, 2527, 2228, 695, 2399], [3876, 3998, 1524, 2473, 3732, 1247, 4977, 3759, 3624], [1067, 2830], [4002, 360, 3384, 3308, 1616, 3629, 2832, 1884, 4269, 4977, 3759, 3624], [3213, 3798, 1069, 503, 2836, 4663, 4927], [2552, 137, 3924, 279, 316, 4503, 3452, 4977, 3759, 3624], [477, 1058, 3958, 4423, 632, 4738, 4345, 4335, 66, 2399], [2683, 1699, 317, 1964, 581, 2917, 834, 3170, 4910, 809, 1110], [3544, 1108, 3417, 2372, 3529, 3071, 3384, 4093, 2388, 331, 1919, 922, 2887, 3897], [141, 1671, 2278, 4253, 296, 414, 91, 4624, 3496, 2399], [128, 960, 4676, 3262, 479, 4889, 17, 4037], [3638], [1431, 1451, 812, 221, 222, 791, 4817, 4977, 3759, 3624], [2552, 3738, 2977, 4980, 2690, 3704, 4977, 3759, 3624], [1281, 2572, 2864, 1033, 2204], [4921, 4054, 3687, 1094, 63, 2565, 4908, 3575, 1083, 1094, 63, 2565, 4908], [1881, 2310, 439, 4043, 3080, 4977, 3759, 3624], [4071, 2269, 3704, 1631, 2552, 4977, 3128, 3716, 4977, 3759, 3624], [485, 431, 3118, 317, 1631, 2552, 2526, 70, 4977, 3759, 3624], [3482, 3882, 4830, 1175, 2218, 3877, 4977, 3759, 3624], [1109, 2664, 3384, 2310, 1332, 4685, 380], [2836, 4663, 3422, 3213, 3746, 3629], [786, 335, 2414, 1984, 4120, 70, 2827, 3505, 3624, 4977, 3759, 3624], [1148, 810, 253, 1956, 4977, 4805, 4269, 2399], [2552, 121, 1773, 3879, 2311, 3765, 3904, 4566, 538, 4977, 3759, 3624], [2564, 2724, 732, 2157, 4896, 3001, 2324, 4733, 2177, 3687, 1961, 2528, 2399], [482, 3599, 1630, 1241, 3633, 35, 4977, 3759, 3624], [637, 4023, 4345, 17, 1969, 3977, 4003], [494, 581, 2426, 1058, 629, 4977, 3759, 3624], [60, 3421, 2397, 1758, 2674, 4377, 2399], [3383, 4431, 128], [2093, 4081, 3635, 4462, 1798, 389, 4617, 2042, 540], [3749, 2474, 2270, 1227, 386, 3860, 1382, 3213, 2103, 2468, 1524], [146, 2724, 4947, 499, 2380, 2480, 2552, 479], [2153, 652, 2251, 4246, 2474, 4298, 1302, 2552, 4409, 2399], [1051, 4406, 649, 1529, 2552, 288, 377], [1530, 3633, 3709, 2041, 551, 3735, 2399], [1802, 718, 2873, 2543, 971], [2418, 908, 1614, 76, 4416, 336, 1663, 2418, 908, 328, 2099, 3946, 359, 3918], [3935, 3506, 85, 3749], [3076, 641, 751, 820, 1243, 3624, 42, 4977, 3759, 3624], [3022, 2269, 235, 2686, 4977, 3759, 3624], [1298, 118, 2820, 2651, 3021, 3343, 4977, 3759, 3624], [768, 3872, 4559, 2129, 3697, 3446, 142, 4197, 60, 1768], [1583, 1884, 2451, 3038, 288, 4980, 4977, 3759, 3624], [4800, 3198, 3322, 2054, 3459, 890, 2254, 2403, 3159, 2828, 4090, 1266], [834, 2552, 544, 2041, 128, 3893, 380, 3269, 1802, 2399], [543, 3221, 2397, 288, 3806, 3193], [3431, 3710, 1671, 70, 4409, 68, 3479, 2552], [1768, 105, 2461, 2552, 4037, 2474, 857, 940, 4977, 3759, 3624], [3327, 2664, 4132, 2358, 271, 804, 4694, 4580, 4977, 3759, 3624], [1735, 2675, 3626, 4977, 3759, 3624], [3893, 1850, 1736, 1802, 2204, 2412, 3050], [3737, 1676, 4197, 3101, 313, 4977, 3759, 3624], [3624, 380, 3668, 4977, 3759, 3624], [3384, 2565, 4468, 1799, 281, 2864, 3458, 2501, 3120, 4977, 3759, 3624], [3448, 1457, 1961, 3231, 2064, 1067, 414, 4785], [596, 2279, 4406, 170, 3893, 2402, 1354, 2572], [4284, 160, 2908, 4205, 3779, 4813, 3011, 4977, 3759, 3624], [2552, 4740, 251, 2377, 1659, 3709, 4931, 2560, 2399], [325, 2148, 4883, 1883, 2844, 2552], [175, 2552, 3452, 380, 4502, 4667, 2940, 4977, 3759, 3624], [4907, 1850, 485, 318, 1635, 2754, 163, 1956], [4766, 3838, 4360, 4253, 1779, 4977, 3759, 3624], [4303, 2467, 1233, 1530, 3100, 614, 4977, 3759, 3624], [83, 3446, 379, 2552, 48, 738, 4261], [1802, 2883, 1712, 3308, 3659, 4471, 2416, 2081, 4977, 3759, 3624], [3083, 2996, 2552, 3097, 1902, 4779, 4977, 3759, 3624], [1631, 2552, 812, 17, 1914, 317], [1096, 1799, 4919, 220, 1491, 1274, 2397, 4571, 4977, 3759, 3624], [17, 2269, 3798, 3514, 2269, 4409, 1348, 4551, 3798, 3514, 4386, 702, 2955, 1631, 136, 85, 3473, 2883, 2588, 259, 2013], [3673, 25, 2204, 2388, 1027], [888, 1354, 139, 768, 2940, 3869, 4309], [414, 3793, 4638, 4258, 1984, 4977, 3759, 3624], [2552, 1750, 930, 4676, 697, 4766, 4977, 3759, 3624], [4966, 4310, 1711, 2552, 4062, 1790], [1276, 572, 1762, 84, 1909, 3484, 2458, 1731], [4235, 3893, 2204], [3269, 514, 3755, 3989, 2860, 779, 3521, 4977, 3759, 3624], [41, 1940, 2921, 389, 1225, 2474, 901, 398, 748, 1733, 4198, 2399], [1631, 2552, 1850, 2268, 2940, 1931, 2180, 3980, 68, 3827, 4977, 3759, 3624], [1527, 2883, 1473, 4566, 4551, 4977, 3759, 3624], [4825, 1636, 4689, 1699, 2996, 4453, 4977, 3759, 3624], [1631, 2552, 4088, 2565, 208, 3749, 1505, 3223, 3155, 1961, 3922, 2278, 3444, 4977, 3759, 3624], [2708, 236, 2552, 4830, 3940, 449, 4977, 3759, 3624], [4678, 583, 2913, 317, 4086, 3567], [2552, 2474, 808], [1530, 2998, 4598, 3709, 3262, 494, 2399], [3001, 3718, 1235, 3305, 1030, 140, 1683, 2552, 1997, 1855, 3099, 3783, 4498], [1563, 401, 2023, 2427, 3237, 1094, 783], [1583, 277, 4485, 1642, 3349, 768], [884, 2077, 2077, 4317, 1928], [3301, 1767, 2813, 1364, 1906, 1274, 146, 2048, 3895, 1788, 4977, 3759, 3624], [1293, 3749, 1505, 2122, 2399], [2901, 119, 3793, 1949, 4962, 3773, 4003, 500, 3724], [4680, 3767, 4919, 3170, 4082, 3504, 3756, 1171], [1760, 1058, 2572, 2247], [3295, 4438, 701, 458, 2595, 4119, 2458, 1157], [88, 3860, 3067, 2574], [4339, 1671, 4685, 2474, 25, 761, 4479, 3728], [2262], [2527, 3446, 1273, 575, 1328, 3787], [2487, 1392, 3872, 3624, 2099, 158, 4977, 3759, 3624], [2552, 3266, 865, 3821, 2860, 4086], [3585, 2632, 1764, 336, 3074, 4977, 3759, 3624], [3543, 4463, 1225, 943, 2861, 2406, 2552, 1728], [183, 4023, 4345, 2113, 1902, 2552, 313], [1616, 4738, 1410, 4839, 761, 2552, 1901, 2399], [2567, 1671, 335, 1947, 3182, 934, 3645, 3452, 4977, 3759, 3624], [3354, 2389, 4210], [563, 259, 1076, 2397, 377, 4977, 3759, 3624], [2055, 4325, 2683, 3812, 388, 1537, 2821, 4972, 121, 2399], [791, 315, 3237, 3753, 488, 2747, 34, 3599, 4977, 3759, 3624], [4685, 3749, 3223, 4377, 1253, 786, 2572], [296, 2724, 2510, 718, 1802, 2073, 1382, 372], [3203, 1964, 4573, 328, 1576, 4889, 1718, 4694, 1894, 2381, 414], [416, 825, 929, 136, 2611, 448, 3166, 3227, 1058, 2793, 3718, 3791], [3749, 4492, 3213, 357, 4927], [3423, 2247, 2552, 3659, 1160, 3254, 356, 4977, 3759, 3624], [70, 1096, 3109, 4461, 2570, 1058, 4977, 3759, 3624], [494, 1608, 57, 984, 2318, 70], [1268, 2564, 449, 4841, 375, 4225, 4134, 4977, 3759, 3624], [1226, 2384, 4841, 121, 4081, 4383, 4383], [1063, 723, 1137, 1041, 1736, 2397, 4977, 3759, 3624], [], [947, 2996, 67, 1902, 947, 4119, 2370, 1258], [2728, 55, 2292, 4253, 32, 252, 1452, 3444, 4120, 1058], [3213, 3348, 3020, 2543, 1881, 2139, 2399], [1682, 3467, 3970, 2660, 3872, 3108, 4269, 2294, 4977, 3759, 3624], [4824, 3724, 4956, 2872, 581, 2176], [2592, 2949, 500, 1887, 3631, 530, 809, 4235, 2456, 3724, 2399], [313, 3762, 1801, 2449, 328, 2200, 1577, 4080], [17, 2674, 4463, 4261, 613], [2552, 3217, 2965, 2820, 479, 4713, 4685, 4566, 273, 4977, 3759, 3624], [4683, 3448, 2234, 2552, 3182, 4193, 17, 613, 2399], [3999, 4578, 317, 2552], [4702, 1292, 3893, 1802, 1338, 342, 4246], [457, 887, 2270, 2820, 1636, 1281, 865], [2306, 4815, 1001, 92, 1935, 1200, 1019, 3922, 4766], [2127, 4463, 804, 380, 2552, 60], [4685, 1887, 1631, 2552, 3198, 3827, 1446, 2066, 1281, 597, 4977, 3759, 3624], [3229, 1326, 2243, 252, 4118, 4298, 1326, 1802, 3718], [414, 581, 2456, 1659, 2393, 252, 1593, 3162, 2828, 3452, 4977

In [51]:
## embedding representation

sent_length = 20
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0, ..., 2412, 2630, 3918],
       [   0,    0,    0, ..., 2456, 2000, 2399],
       [   0,    0,    0, ..., 2311,  288, 1663],
       ...,
       [   0,    0,    0, ..., 4977, 3759, 3624],
       [   0,    0,    0, ..., 3324,  335, 2286],
       [   0,    0,    0, ..., 3765, 2128, 2275]], dtype=int32)

In [52]:
## Creating model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_shape=(sent_length,)))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 313,001 (1.19 MB)

 Trainable params: 313,001 (1.19 MB)

 Non-trainable params: 0 (0.00 B)

None

In [53]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [54]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [55]:
## model training

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 8s 17ms/step - accuracy: 0.8941 - loss: 0.2780 - val_accuracy: 0.9144 - val_loss: 0.2058
Epoch 2/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9465 - loss: 0.1411 - val_accuracy: 0.9153 - val_loss: 0.2014
Epoch 3/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9694 - loss: 0.0854 - val_accuracy: 0.9195 - val_loss: 0.2074
Epoch 4/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9835 - loss: 0.0504 - val_accuracy: 0.9223 - val_loss: 0.2495
Epoch 5/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9910 - loss: 0.0305 - val_accuracy: 0.9187 - val_loss: 0.3084
Epoch 6/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9962 - loss: 0.0157 - val_accuracy: 0.9162 - val_loss: 0.3934
Epoch 7/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9973 - loss: 0.0114 - val_accuracy: 0.9162 - val_loss: 0.4254
Epoch 8/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.9169 - val_loss: 0.4930
Epoch 9/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9984 - loss: 0.0064 - val_accuracy: 0.9099 - val_loss: 0.4852
Epoch 10/10
212/212 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9985 - loss: 0.0055 - val_accuracy: 0.9115 - val_loss: 0.5055

In [57]:
y_pred = model.predict(X_test)

209/209 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

In [58]:
y_pred = np.where(y_pred > 0.5, 1, 0)

In [59]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[3093,  317],
       [ 274, 2996]])

In [61]:
accuracy_score(y_test, y_pred)

0.9115269461077844